import{mobiles,software,androidSolutions,appleSolutions,cyberTools,pricing}from'../database/data.js';
const root=location.pathname.includes('/pages/')?'..':'.';const page=document.body.dataset.page;
const visualStyle=document.createElement('style');visualStyle.textContent=`.robot-scene:after{content:"";position:absolute;inset:-20px;background:url('${root}/images/hero-robot.svg') center/contain no-repeat;opacity:.43;pointer-events:none;z-index:-1}.cyber-hero{background-image:url('${root}/images/cyber-grid.svg'),radial-gradient(circle at 78% 40%,#ff781f20,transparent 26%);background-size:cover,auto;background-position:center}`;document.head.append(visualStyle);
const nav=[['Home','index.html','home'],['Mobiles','pages/mobiles.html','mobiles'],['Android','pages/android.html','android'],['Apple','pages/apple.html','apple'],['Downloads','pages/downloads.html','downloads'],['Cyber Security','pages/cyber-security.html','cyber'],['Contact','pages/contact.html','contact']];
const link=([name,path,id])=>`<a class="${page===id?'active':''}" href="${root}/${path}">${name}</a>`;
document.querySelector('#site-header').innerHTML=`<div class="site-header"><a class="brand" href="${root}/index.html">TECH<b>FIX</b></a><span class="founder">FOUNDER — MIAN AHMAD</span><nav class="nav">${nav.map(link).join('')}</nav><div class="header-actions"><button class="icon-btn" data-open-search aria-label="Search">⌕</button><a class="wa" target="_blank" rel="noopener" href="https://wa.me/966568152404">WhatsApp</a><button class="icon-btn menu" data-menu aria-label="Open menu">☰</button></div></div>`;
document.querySelector('#site-footer').innerHTML=`<div class="footer-top"><div><a class="brand" href="${root}/index.html">TECH<b>FIX</b></a><p>Premium mobile software resources, repair solutions and technical learning from TechFix Software EXP.</p><p class="eyebrow">MIAN AHMAD — FOUNDER</p></div><div><p class="eyebrow">EXPLORE</p><div class="footer-links">${nav.slice(1).map(link).join('')}</div></div><div><p class="eyebrow">CONNECT</p><div class="footer-links"><a href="mailto:officialtechfix786@gmail.com">officialtechfix786@gmail.com</a><a target="_blank" rel="noopener" href="https://wa.me/966568152404">WhatsApp +966 56 815 2404</a><a target="_blank" rel="noopener" href="https://www.youtube.com/@TechfixSoftwareEXP">YouTube</a><a target="_blank" rel="noopener" href="https://github.com/officialtechfix786">GitHub</a></div></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} TechFix Software EXP. All rights reserved.</span><span>Built for precision.</span></div>`;
document.body.insertAdjacentHTML('beforeend',`<div class="search-overlay" id="search-overlay"><div class="search-box"><header><p class="eyebrow">SEARCH TECHFIX</p><button class="icon-btn" data-close-search>×</button></header><input id="global-search" autofocus placeholder="Search devices, tools, solutions…"><div class="search-results" id="search-results"></div></div></div><button class="back-top" aria-label="Back to top">↑</button>`);
const logo=s=>`<div class="software-mark">${s.split(' ').map(x=>x[0]).join('').slice(0,2)}</div>`;const rating=`<div class="rating">★★★★★ <span>4.9/5</span></div>`;
function renderSoftware(list,target){document.querySelector(target).innerHTML=list.map(s=>`<article class="software-card">${logo(s.name)}<h3>${s.name}</h3><span class="pill">${s.category} · ${s.version}</span><p>${s.desc}</p>${rating}<a href="${s.url}" target="_blank" rel="noopener">Official website ↗</a></article>`).join('')}
function renderMobiles(list){document.querySelector('#mobile-grid').innerHTML=list.map(m=>`<article class="device-card"><header><div class="device-mark">${m.brand.slice(0,2).toUpperCase()}</div><div><h3>${m.model}</h3><small>${m.brand}</small></div></header><div class="specs"><span><b>Android</b><br>${m.android}</span><span><b>Chipset</b><br>${m.chip}</span><span><b>Boot</b><br>${m.boot}</span><span><b>Solutions</b><br>${m.solutions.join(', ')}</span></div><div class="rating">★★★★★ ${m.rating}/5</div></article>`).join('')}
function renderSolutions(items,target){document.querySelector(target).innerHTML=items.map(s=>`<article class="solution-card"><span class="solution-no">${s.no}</span><h3>${s.brand}</h3><ul>${s.items.map(x=>`<li>${x}</li>`).join('')}</ul><div class="rating">★★★★★ 4.9/5</div></article>`).join('')}
function filters(target,items,cb){const groups=['All',...new Set(items.map(x=>x.category||x.brand))];document.querySelector(target).innerHTML=groups.map(x=>`<button class="${x==='All'?'active':''}" data-filter="${x}">${x}</button>`).join('');document.querySelector(target).addEventListener('click',e=>{if(!e.target.dataset.filter)return;document.querySelectorAll(`${target} button`).forEach(b=>b.classList.toggle('active',b===e.target));cb(e.target.dataset.filter==='All'?items:items.filter(x=>(x.category||x.brand)===e.target.dataset.filter))})}
if(page==='home')renderSoftware(software.slice(0,3),'#featured-software');
if(page==='mobiles'){renderMobiles(mobiles);filters('#mobile-filters',mobiles,renderMobiles)}
if(page==='downloads'){renderSoftware(software,'#software-grid');filters('#software-filters',software,x=>renderSoftware(x,'#software-grid'))}
if(page==='android'){document.querySelector('#brand-cloud').innerHTML=androidSolutions.map(x=>`<span>${x.brand}</span>`).join('');renderSolutions(androidSolutions,'#android-solutions')}
if(page==='apple')renderSolutions(appleSolutions,'#apple-solutions');
if(page==='cyber')document.querySelector('#cyber-grid').innerHTML=cyberTools.map(t=>`<article class="cyber-card"><div class="cyber-mark">${t.name.slice(0,2).toUpperCase()}</div><h3>${t.name}</h3><p>${t.desc}</p><p class="pill">Authorized learning only</p><p>To learn this tool professionally, contact TechFix Software EXP.</p><a href="${t.url}" target="_blank" rel="noopener">Official website ↗</a></article>`).join('');
const all=[...mobiles.map(x=>({type:'Mobile',title:`${x.brand} ${x.model}`,text:`${x.android} · ${x.solutions.join(', ')}`,url:`${root}/pages/mobiles.html`})),...software.map(x=>({type:'Software',title:x.name,text:x.desc,url:`${root}/pages/downloads.html`})),...androidSolutions.map(x=>({type:'Solution',title:`${x.brand} Solutions`,text:x.items.join(', '),url:`${root}/pages/android.html`})),...pricing.map(x=>({type:'Price',title:x[0],text:`Professional guideline: ${x[1]}`,url:`${root}/pages/contact.html`}))];
const overlay=document.querySelector('#search-overlay');document.querySelectorAll('[data-open-search]').forEach(b=>b.onclick=()=>{overlay.classList.add('open');setTimeout(()=>document.querySelector('#global-search').focus(),20)});document.querySelector('[data-close-search]').onclick=()=>overlay.classList.remove('open');document.querySelector('#global-search').oninput=e=>{const q=e.target.value.toLowerCase().trim();const results=q?all.filter(x=>(x.title+x.text+x.type).toLowerCase().includes(q)).slice(0,8):[];document.querySelector('#search-results').innerHTML=results.map(r=>`<a href="${r.url}" class="search-result"><small>${r.type}</small><b>${r.title}</b><span>${r.text}</span></a>`).join('')|| (q?'<p class="search-result">No matching TechFix resources found.</p>':'')};
document.querySelector('[data-menu]').onclick=()=>{const n=document.querySelector('.nav');n.style.cssText=n.style.display==='flex'?'':'display:flex;position:absolute;top:66px;left:0;right:0;flex-direction:column;align-items:stretch;padding:20px;background:#0e1219;border-bottom:1px solid var(--line)';};
const up=document.querySelector('.back-top');addEventListener('scroll',()=>{document.querySelector('.site-header').classList.toggle('scrolled',scrollY>20);up.classList.toggle('visible',scrollY>500)});up.onclick=()=>scrollTo({top:0,behavior:'smooth'});document.querySelector('#contact-form')?.addEventListener('submit',e=>{e.preventDefault();e.currentTarget.querySelector('.form-result').textContent='Thanks — your message is ready to send. We’ll respond through your provided contact details.';e.currentTarget.reset()});addEventListener('load',()=>document.querySelector('.preloader')?.classList.add('done'));
