export const mobiles=[
{brand:'Samsung',model:'Galaxy S24 Ultra',android:'Android 14',chip:'Snapdragon 8 Gen 3',boot:'Download Mode',solutions:['FRP','Firmware','Network'],rating:'4.9'},
{brand:'Xiaomi',model:'Redmi Note 13 Pro',android:'Android 13',chip:'Snapdragon 7s Gen 2',boot:'Fastboot',solutions:['FRP','Flash','Unlock'],rating:'4.8'},
{brand:'Oppo',model:'Reno 11',android:'Android 14',chip:'Dimensity 7050',boot:'Recovery',solutions:['FRP','Flash','Drivers'],rating:'4.8'},
{brand:'Vivo',model:'V30',android:'Android 14',chip:'Snapdragon 7 Gen 3',boot:'Fastboot',solutions:['FRP','Firmware','Network'],rating:'4.7'},
{brand:'Google',model:'Pixel 8 Pro',android:'Android 14',chip:'Tensor G3',boot:'Fastboot',solutions:['Flash','Boot','Network'],rating:'4.9'},
{brand:'Tecno',model:'Camon 30',android:'Android 14',chip:'Helio G99',boot:'Recovery',solutions:['FRP','Flash','IMEI'],rating:'4.7'},
{brand:'Infinix',model:'Note 40 Pro',android:'Android 14',chip:'Helio G99',boot:'Recovery',solutions:['FRP','Flash','Drivers'],rating:'4.7'},
{brand:'OnePlus',model:'12R',android:'Android 14',chip:'Snapdragon 8 Gen 2',boot:'Fastboot',solutions:['Flash','Unlock','Boot'],rating:'4.8'},
{brand:'Realme',model:'12 Pro+',android:'Android 14',chip:'Snapdragon 7s Gen 2',boot:'Fastboot',solutions:['FRP','Flash','Network'],rating:'4.8'}];
export const software=[
{name:'3uTools',category:'Apple',version:'Latest',url:'https://www.3u.com',desc:'All-in-one iOS device management and flashing utility.'},{name:'iTunes',category:'Apple',version:'Latest',url:'https://support.apple.com/itunes',desc:'Official Apple software for device sync, backup and restore.'},{name:'iMazing',category:'Apple',version:'Latest',url:'https://imazing.com',desc:'Professional iPhone and iPad device manager.'},{name:'Odin',category:'Samsung',version:'Latest',url:'https://samsungodin.com',desc:'Samsung firmware flashing utility resource.'},{name:'SP Flash Tool',category:'MTK',version:'Latest',url:'https://spflashtool.com',desc:'Firmware flash tool for MediaTek devices.'},{name:'Mi Flash',category:'Xiaomi',version:'Latest',url:'https://xiaomiflashtool.com',desc:'Fastboot firmware flashing resource for Xiaomi devices.'},{name:'ADB Platform Tools',category:'ADB',version:'Latest',url:'https://developer.android.com/tools/releases/platform-tools',desc:'Official Android Debug Bridge and Fastboot package.'},{name:'QFIL',category:'Qualcomm',version:'Latest',url:'https://qpsttool.com',desc:'Qualcomm Flash Image Loader software resource.'},{name:'QPST',category:'Qualcomm',version:'Latest',url:'https://qpsttool.com',desc:'Qualcomm Product Support Tools resource.'},{name:'SamFW Tool',category:'Samsung',version:'Latest',url:'https://samfw.com',desc:'Samsung utility and firmware information portal.'},{name:'Chimera Tool',category:'Unlock',version:'Latest',url:'https://chimeratool.com',desc:'Professional phone servicing software.'},{name:'Hydra Tool',category:'Unlock',version:'Latest',url:'https://www.hydra-dongle.com',desc:'Mobile phone repair and servicing platform.'},{name:'Android Utility',category:'ADB',version:'Latest',url:'https://androidutility.com',desc:'Android device maintenance utility.'},{name:'MTK Client',category:'MTK',version:'Latest',url:'https://github.com/bkerler/mtkclient',desc:'Open-source MediaTek service client.'}];
export const androidSolutions=['Samsung','Xiaomi','Oppo','Vivo','Realme','Tecno','Infinix','Huawei','Honor','Motorola','Google','Nothing'].map((brand,i)=>({brand,no:String(i+1).padStart(2,'0'),items:['FRP and account guidance','Official firmware workflows','Boot and recovery paths','Driver and tool requirements']}));
export const appleSolutions=[['Restore & Recovery','iPhone and iPad recovery-mode restore paths'],['DFU & Firmware','Professional firmware and DFU guidance'],['Activation Support','Activation workflow and device setup assistance'],['Backup & Transfer','Safe backup, migration and restore guidance'],['Hardware Features','Face ID and Touch ID diagnostic direction'],['Apple Watch & Mac','Maintenance resources for the Apple ecosystem']].map((x,i)=>({brand:x[0],no:String(i+1).padStart(2,'0'),items:[x[1],'Official tools and documentation','Professional notes before service']}));
export const cyberTools=[['Kali Linux','Security-focused Linux distribution','https://www.kali.org'],['Burp Suite','Web application security testing platform','https://portswigger.net/burp'],['Metasploit','Penetration-testing framework','https://www.metasploit.com'],['Nmap','Network discovery and security auditing','https://nmap.org'],['Wireshark','Network protocol analyzer','https://www.wireshark.org'],['Hydra','Authorized credential-testing utility','https://github.com/vanhauser-thc/thc-hydra'],['SQLMap','Authorized SQL injection testing tool','https://sqlmap.org'],['Hashcat','Password recovery and auditing utility','https://hashcat.net/hashcat'],['Aircrack-ng','Wi-Fi security auditing suite','https://www.aircrack-ng.org'],['John the Ripper','Password security auditing tool','https://www.openwall.com/john'],['Gobuster','Content discovery utility','https://github.com/OJ/gobuster'],['Dirsearch','Web path discovery utility','https://github.com/maurosoria/dirsearch'],['Nikto','Web server scanner','https://github.com/sullo/nikto'],['Subfinder','Subdomain discovery tool','https://github.com/projectdiscovery/subfinder'],['FFUF','Web fuzzing tool','https://github.com/ffuf/ffuf']].map(x=>({name:x[0],desc:x[1],url:x[2]}));
export const pricing=[['Android FRP','1000–1500'],['Flash','1000–2000'],['IMEI Repair','2500–4000'],['Network Repair','2500–3500'],['Boot Repair','2000–3000'],['Apple Restore','1500'],['Apple Flash','2000'],['Passcode','3000'],['Activation','3500'],['iCloud Related','6000+']];
